### ISSUE TITLE
No contacts

### ISSUE THREAD

**Issue by philipptrepte** [hocinebib/PisaPy#1]
When I am using 'src/PisaAuto_file.py' for a folder with multiple .pdb files, the script does not detect if there are 'No contacts' detected between the chains and 'Step 3-Running PISA' continues indefinitely. Is it possible to check for 'No contacts' and then proceed to the next pdb file?

**Comment by hocinebib** [comment]
Hi, sorry for the late reply can you send me one of the pdb files with no contacts ?

**Comment by philipptrepte** [comment]
Thanks for the quick reply and the great tool :) 
Attached you find a pdb file with no contacts.

**Comment by hocinebib** [comment]
Hi I don't see the attached file

**Comment by philipptrepte** [comment]
Apparently you can't attach pdb files directly in GitHub. Any suggestion how to share the file?

**Comment by hocinebib** [comment]
here is my email : hocine.meraouna@gmail.com

**Comment by hocinebib** [comment]
Should be working now, can you test and tell me if it's working fine for you ? thank you :)

**Comment by philipptrepte** [comment]
Perfect! It is working beautiful now. Thanks for the quick fix :)

**Comment by hocinebib** [comment]
happy to help :)
